In [1]:
#Write a NumPy program to reverse an array (first element becomes last). 
import numpy as np
a=[]
value=int(input("enter the size of array"))
for i in range(value):
    val=int(input("enter number"))
    a.append(val)
arr=np.array(a)
#arr = np.array([10,20,30,40,50])
print("Original Array: \n", arr)

arr_reversed = np.flip(arr)
print("\nReversed Array: \n", arr_reversed)

enter the size of array3
enter number1
enter number2
enter number3
Original Array: 
 [1 2 3]

Reversed Array: 
 [3 2 1]


In [2]:
#Write a NumPy program to extract all odd numbers from an array 
a=[]
value=int(input("enter the size of array"))
for i in range(value):
    val=int(input("enter number"))
    a.append(val)
arr=np.array(a)
#arr=np.array([1,2,3,4,5,6,7,8,9])
odds= arr[arr%2==1]
print(odds)

enter the size of array3
enter number1
enter number2
enter number3
[1 3]


In [51]:
#1 on the border and 0 inside 
import numpy as np
x = np.ones((5,5))
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1]=0
print(x)

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [53]:
#append values at the end of the string 

import numpy as np

# creating an array
arr = np.array([1, 8, 3, 3, 5])


# appending to the array
arr = np.append(arr, [7,89,98])
print('Array after appending : ', arr)


Original Array :  [1 8 3 3 5]
Array after appending :  [ 1  8  3  3  5  7 89 98]


In [3]:
#median of the flattend array
import numpy as np
a=[]
value=int(input("enter the size of array"))
for i in range(value):
    val=int(input("enter number"))
    a.append(val)
arr=np.array(a)

#arr = np.array([1, 2, 3, 4, 5, 6, 7,8])

median = np.median(arr)
print("\nMedian of the array ")
print(median)


enter the size of array8
enter number1
enter number2
enter number3
enter number4
enter number5
enter number6
enter number7
enter number8

Median of the array 
4.5


In [5]:
#most frequent element
import numpy as np
a=[]
value=int(input("enter the size of array"))
for i in range(value):
    val=int(input("enter number"))
    a.append(val)
arr=np.array(a)
#x = np.array([1,2,3,4,5,45,45,45,45])
print("Original array:")
print(arr)

print("Most frequent value in the above array:")
print(np.bincount(arr).argmax())


enter the size of array3
enter number1
enter number1
enter number2
Original array:
[1 1 2]
Most frequent value in the above array:
1


In [62]:
#comparing two random arrays
x = np.array([45,45,45,45])
y = np.array([45,45,45,45])

if np.array_equal(x,y)==False:
    print("not equal")
else:
    print("equal")


equal


In [64]:
#Write a NumPy program to get the powers of an array values element-wise. 
import numpy as np


# creating the array
sample_array1 = np.arange(5)
sample_array2 = np.arange(0, 10, 2)

print("Original array ")
print("array1 =", sample_array1)
print("array2 =", sample_array2)

# calculating element-wise power
power_array = np.power(sample_array1, sample_array2)

print("power to the array1 and array 2 : ", power_array)


Original array 
array1 = [0 1 2 3 4]
array2 = [0 2 4 6 8]
power to the array1 and array 2 :  [    1     1    16   729 65536]


In [65]:
#Write a NumPy program to add, subtract, multiply, divide arguments element-wise. 
import numpy as np
print("Add:")
print(np.add(1.0, 4.0))
print("Subtract:")
print(np.subtract(1.0, 4.0))
print("Multiply:")
print(np.multiply(1.0, 4.0))
print("Divide:")
print(np.divide(1.0, 4.0))


Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25


In [67]:
#multiplication of 2 matrices 
import numpy as np
# initializing the matrices
matrix1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] 

matrix2 = [ [7, 8, 9], [4, 5, 6],[1, 2, 3]]

# multiplying the two matrices

result = np.dot(matrix1, matrix2)
# printing the result
print(result)

[[ 18  24  30]
 [ 54  69  84]
 [ 90 114 138]]


In [81]:
#replace odd with -1 
import numpy as np  
arr = np.arange(1,10)   

arr[arr%2==1] = -1        

print(arr)

[-1  2 -1  4 -1  6 -1  8 -1]


In [82]:
#same as above but without changing arr
arr = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2 = np.where(arr % 2 == 1, -1,arr) #WHERE CONDITION IS TRUE PUT -1 OTHERWISE PUT ARR THAT IS VALUE OF ELEMENT
print(arr)
print(arr2)

[1 2 3 4 5 6 7 8 9]
[-1  2 -1  4 -1  6 -1  8 -1]


In [88]:
#convert 1D TO 2D
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])


#having dimension 4 x 2
arr1 = arr.reshape(4, 2)
print ('After reshaping having dimension 4x2:')
print (arr1)
print ('\n')

#having dimension 2 x 4
arr2 = arr.reshape(2, 4)
print ('After reshaping having dimension 2x4:')
print (arr2)



After reshaping having dimension 4x2:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


After reshaping having dimension 2x4:
[[1 2 3 4]
 [5 6 7 8]]


In [99]:
#SWAP 2 COLUMNS IN 2D

import numpy as np

my_array = np.arange(9).reshape(3, 3)
print("Original array:")
print(my_array)

# swapping the column with index of

my_array[:, [2, 0]] = my_array[:, [2, 0]]
print("After swapping arrays the last column and first column:")
print(my_array)


Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
After swapping arrays the last column and first column:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [106]:
arr2D = np.array([[11, 12, 13, 11], [21, 22, 23, 24], [31, 32, 33, 34]])
print('2D Numpy Array')
print(arr2D)
  # Reverse contents of each row and column in the Numpy Array

reversedArr = np.flip(arr2D, axis=0)
print('Reversed Array  for rows: \n',reversedArr)

reversedArr1 = np.flip(arr2D, axis=1)
print('Reversed Array  for colums: \n',reversedArr1)


2D Numpy Array
[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]
Reversed Array  for rows: 
 [[31 32 33 34]
 [21 22 23 24]
 [11 12 13 11]]
Reversed Array  for colums: 
 [[11 13 12 11]
 [24 23 22 21]
 [34 33 32 31]]
