In [2]:
#Write a NumPy program to get the numpy version and show numpy build configuration.

#Write a NumPy program to  get help on the add function.

import numpy as np 
print(np. __version__) 

print(np. show_config ())

print(np.info(np.add))

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

In [13]:
#Write a NumPy program to test whether none of the elements of a given array is zero
#taking number from the user and inserting into the array #one dimensional array
import numpy as np
a=[]
value=int(input("enter the size of array"))
for i in range(value):
    val=int(input("enter number"))
    a.append(val)
    
#print(np.all(a))
if np.all(a)==True:
        print("doesnt have zero")
else:   
        print("contains zero")


enter the size of array4
enter number0
enter number0
enter number00
enter number0
contains zero


In [3]:
#Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).
#Write a NumPy program to test element-wise for positive or negative infinity. 
#Write a NumPy program to test element-wise for NaN of a given array. 

import numpy as np
a = np.array([1, 0, np.nan, np.inf])

print("Original array")

print(a)

print("Test a given array element-wise for finiteness :")

print(np.isfinite(a))
print("Test a given array element-wise for infiniteness :")
print(np.isinf(a))

print("Test a given array element-wise for not a number :")
print(np.isnan(a))


Original array
[ 1.  0. nan inf]
Test a given array element-wise for finiteness :
[ True  True False False]
Test a given array element-wise for infiniteness :
[False False False  True]
Test a given array element-wise for not a number :
[False False  True False]


In [4]:
#Write a NumPy program to test element-wise for complex number, real number of a given array.
#Also test if a given number is a scalar type or not. 
import numpy as np
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))
print("Checking for real number:")
print(np.isreal(a))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


In [6]:
#Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays
import numpy as np
x = np.array([3, 5])
y = np.array([2, 5])

print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [14]:
#Write a NumPy program to create an array of 10 zeros, an array of 10 ones, and an array of 10 fives. 
import numpy as np #prints zeros and ones 
arr=np.ones(10)
arr1=np.zeros(10)
arr5=np.ones(10)*5
print(arr)
print(arr1)
print(arr5)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [15]:
#Write a NumPy program to create an array of the integers from 30 to70. 
import numpy as np
array=np.arange(30,71,2)
print("Array of the integers from 30 to70")
print(array)

Array of the integers from 30 to70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [19]:
#Write a NumPy program to create a 3x3 identity matrix. 
import numpy as np
arr=np.identity(3)
print('3x3 matrix:')
print(arr)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
import numpy as np #random number generate 
arr=np.random.rand(5)
print(arr)

[0.62631194 0.84878177 0.28704736 0.48475131 0.21369298]


In [26]:
#Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution. 
import numpy as np
numbers = np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(numbers)

15 random numbers from a standard normal distribution:
[-0.10748621  0.93634793  0.8540689  -0.8758441   0.58710708 -0.375501
  0.25761191 -0.52369706  0.65828569  1.18558259 -0.01861291  0.68866504
 -1.24742325 -1.05884496 -0.59686867]


In [33]:
#Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values 
#except the first and last. 
import numpy as np
v = np.arange(15,55)
print("Original vector:")
print(v)
print("All values except the first and last of the said vector:")
print(v[1:-1])

Original vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
All values except the first and last of the said vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [36]:
#Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50. 
import numpy as np
vector=np.arange(5,50,10)
print(vector)

[ 5 15 25 35 45]


In [38]:
#Write a NumPy program to multiply the values of two given vectors. 
import numpy as np
x = np.array([1, 8, 3, 5])
y=np.array([4,9,8,1])
result=x*y
print("multiplication value is ",result)

multiplication value is  [ 4 72 24  5]


In [55]:
#Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21. 
import numpy as np
m= np.arange(10,22).reshape((3, 4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[42 45 48 51]


In [52]:
#diagnol as 1,2,3,4,5
import numpy as np #gives what we have to enter in a diagonal 
arr=np.diag((1,2,3,4,5))
print(arr)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[1 2 3 4 5]


In [42]:
#Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of an given array. 

import numpy as np
x = np.array([[0,1],[2,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]
