In [15]:
import numpy as np
myarr=np.array([[1,2,3,4,5],[7,8,9,10,11]])
myarr.shape

(2, 5)

In [16]:
#taking number from the user and inserting into the array #one dimensional array
import numpy as np
a=[]
value=int(input("enter the size of array"))
for i in range(value):
    val=int(input("enter number"))
    a.append(val)
print(a)

enter the size of array1
enter number1
[1]


In [1]:
import numpy as np #prints zeros and ones 
arr=np.ones(4)
arr1=np.zeros((4,4))
arr
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
import numpy as np # gives 1 as diagonal 
arr=np.eye(3,3)
arr
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
import numpy as np #gives what we have to enter in a diagonal 
arr=np.diag((1,2,3,4,5))
print(arr)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [43]:
import numpy as np #random number generate 
arr=np.random.randint(1,10,3)
arr

array([1, 5, 3])

In [47]:
#import numpy as np # gives random value between 0 to 9 where size of range is passed # also makes matrix
arr=np.random.rand(2,3)
arr

array([[0.80600465, 0.77477764, 0.15723582],
       [0.11263357, 0.80344053, 0.95753795]])

In [52]:
import numpy as np
a = ([0,0,0], [0,0,0])
np.empty_like(a)

array([[554511712,       470,         0],
       [        0,         5,   7340144]])

In [53]:
# numpy.full method , fills with the given element 

import numpy as np

a = np.full([2, 2], 67, dtype = int)
print("\nMatrix a : \n", a)

c = np.full([3, 3], 10.1)
print("\nMatrix c : \n", c)





Matrix a : 
 [[67 67]
 [67 67]]

Matrix c : 
 [[10.1 10.1 10.1]
 [10.1 10.1 10.1]
 [10.1 10.1 10.1]]


In [7]:
import numpy as np
a=np.array([[1,2,3],
            [4,5,6],[7,8,9]])

print(a[:2,1:3])


[[2 3]
 [5 6]]
